site_name: "py-typedlogic"
theme:
  name: material
  features:
    - content.tabs.link
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_toc_entry: false
            show_category_heading: false
            toc_depth: 1
            members_order: source
            docstring_style: sphinx
  - mermaid2:
      version: 9.3.0
  - autorefs
  - mknotebooks:
      execute: false
markdown_extensions:
  - admonition
  - codehilite
  - mkdocs-click
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Tutorial:
     - 1. First program: tutorial/01-first-program
     - 2. Using the Python Data Model: tutorial/02-using-python-data-model
  - Concepts:
      - Core concepts: concepts/index.md
      - Data Model: concepts/datamodel.md
      - Decorators: concepts/decorators.md
      - Generators: concepts/generators.md
      - Solvers: concepts/solvers.md
      - Models: concepts/models.md
      - Benchmarks: concepts/benchmarks.md
  - Solvers:
      Solver overview: integrations/solvers/index.md
      Clingo: integrations/solvers/clingo.md
      Z3: integrations/solvers/z3.md
      Souffle: integrations/solvers/souffle.md
      Prover9: integrations/solvers/prover9.md
      SnakeLog: integrations/solvers/snakelog.md
      LLM Solver: integrations/solvers/llm.md
  - Compilers:
      - Compiler overview: conversion/compilers/index.md
      - YAML: conversion/compilers/yaml.md
      - Prolog: conversion/compilers/prolog.md
      - TPTP: conversion/compilers/tptp.md
      - FOL: conversion/compilers/fol.md
      - S-Expression: conversion/compilers/sexpr.md
  - Parsers:
      - Parser overview: conversion/parsers/index.md
      - Python: conversion/parsers/python.md
      - YAML: conversion/parsers/yaml.md
  - Frameworks:
      - OWL-DL:
          - OWL-DL: integrations/frameworks/owldl/index.md
          - Tutorial: integrations/frameworks/owldl/owldl-tutorial
          - Classes: integrations/frameworks/owldl/owltop.md
          - Reasoner: integrations/frameworks/owldl/reasoner.md
      - Pydantic: integrations/frameworks/pydantic
      - SQLModel: integrations/frameworks/sqlmodel.md
  - Command Line: cli.md
  - FAQ: troubleshooting.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md
site_url: https://py-typedlogic.github.io/py-typedlogic/
repo_url: https://github.com/py-typedlogic/py-typedlogic/
