%% Predicate Definitions
% Protein(name: str)
% ModifiedProtein(protein: Protein, modification: ModificationType, site: Optional, active: bool)
% Complex(name: Optional)
% Kinase(protein: Protein)
% Phosphatase(protein: Protein)
% GTPase(protein: Protein)
% GEF(protein: Protein, target: Protein)
% GAP(protein: Protein, target: Protein)
% Ligand(name: str)
% Receptor(protein: Protein)
% LigandReceptorBinding(ligand: Ligand, receptor: Receptor, active: bool)
% Activation(upstream: Protein, downstream: Protein)
% PhosphorylationEvent(kinase: Protein, substrate: Protein, site: str)
% Translocation(protein: Protein, from_compartment: str, to_compartment: str)
% Compartment(name: str)
% ProteinLocation(protein: Protein, compartment: Compartment)