[ForAll([lhs, rhs, parent],
        Implies(And(Parent(lhs, parent),
                    Parent(rhs, parent),
                    lhs != rhs),
                Disjoint(lhs, rhs))),
 ForAll([cls, slot],
        Implies(And(ClassDefinition(cls),
                    SlotDefinition(slot),
                    Not(ClassSlot(cls, slot))),
                InvalidClassSlot(cls, slot))),
 ForAll([cls, slot_expression],
        Implies(SlotUsage(cls, slot_expression),
                Parent(cls, slot_expression))),
 ForAll([cls, slot_expression],
        Implies(Attribute(cls, slot_expression),
                Parent(cls, slot_expression))),
 ForAll([element, parent],
        Implies(IsA(element, parent),
                Parent(element, parent))),
 ForAll([element, parent],
        Implies(Mixin(element, parent),
                Parent(element, parent))),
 ForAll([cls, slot, parent],
        Implies(And(Parent(cls, parent),
                    ClassSlot(parent, slot)),
                Parent(cls, slot)))]