name: Auto-deployment of Documentation
on:
  push:
    branches: [ main ]
jobs:
  build-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Set up Python 3.
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install Poetry.
      uses: snok/install-poetry@v1.3.1

    - name: Install dependencies.
      run: |
        poetry install

    #----------------------------------------------
    #  Create documentation and deploy.
    #----------------------------------------------
    - name: Create local docs
      run: |
        touch docs/.nojekyll
        poetry run mkdocs gh-deploy
